[package]
name = "influxdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1.4"
influxdb-line-protocol = "1"
reqwest = { version = "0.11", features = ["gzip"] }
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"
url = "2.4"
